### ISSUE TITLE
カラムの移動とリネームを同時に行うと Column not foundが出る

### ISSUE THREAD

**Issue by howyi** [howyi/conv#10]
before
```yaml
comment: 'User management table'
column:
  user_id:
    type: int(11)
    comment: 'User ID'
  name:
    type: varchar(30)
    comment: 'User name'
    attribute: [nullable]
  age:
    type: int(11)
    comment: 'User age'
    attribute: [nullable]
```
after
```yaml
comment: 'User management table'
column:
  namae:
    type: varchar(30)
    comment: 'User name'
    attribute: [nullable]
  user_id:
    type: int(11)
    comment: 'User ID'
  age:
    type: int(11)
    comment: 'User age'
    attribute: [nullable]
```

error
```bash
% ./debug check:alter
Column tbl_user.name is missing. Choose an action.
  [0] dropped
  [1] renamed (namae)
 > renamed (namae)
TableName : tbl_user
    modified:  name -> namae
    modified:  user_id
実行クエリ
ALTER TABLE `tbl_user`
  CHANGE `name` `namae` varchar(30) COMMENT 'User name',
  MODIFY COLUMN `user_id` int(11) NOT NULL COMMENT 'User ID' AFTER `name`;


  [PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'tbl_user'


check:alter
```
